name: VitalBroadcast
version: @version@
main: dev.meinel.leo.vitalwelcome.VitalBroadcast
api-version: 1.17
authors: [ Leopold Meinel ]
description: Broadcasts a welcome message when new players join.
commands:
  broadcast:
    description: "Main command"
    usage: "/broadcast"
permissions:
  vitalbroadcast.broadcast:
    description: "Permission to send broadcast"
    default: op